name: Data Validation

on:
  push:
    paths:
      - 'data/**'
      - 'src/data/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Validate data schema
      run: |
        # This is a placeholder for data validation
        # In a real project, you would run your data validation scripts here
        echo "Running data validation checks..."
        # Example validation script (would be in your project)
        # python src/data/validate_data.py
        
    - name: Generate data report
      run: |
        # Generate a report of the data validation
        echo "Data validation completed successfully" > data_validation_report.txt
        
    - name: Upload data validation report
      uses: actions/upload-artifact@v3
      with:
        name: data-validation-report
        path: data_validation_report.txt 